BEGIN 
sys.dbms_logrep_imp.instantiate_schema(schema_name=>SYS_CONTEXT('USERENV','CURRENT_SCHEMA'), export_db_name=>'G5E60EBADF0D95A_ANTPRD', inst_scn=>'39110999547237');
COMMIT; 
END;
/
CREATE SEQUENCE  "DEMO"."CONTACT_US_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
CREATE SEQUENCE  "DEMO"."UXI_DATA_SRC_LU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
CREATE SEQUENCE  "DEMO"."UXI_AUTHN_METHODS_LU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
CREATE TABLE "DEMO"."UXI_DATA_SRC_LU" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"POSSIBLE" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 'Y' NOT NULL ENABLE, 
	 CONSTRAINT "UXI_DATA_SRC_LU_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."DATABASECHANGELOGLOCK" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LOCKED" NUMBER(1,0) NOT NULL ENABLE, 
	"LOCKGRANTED" TIMESTAMP (6), 
	"LOCKEDBY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."DATABASECHANGELOG" 
   (	"ID" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"AUTHOR" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DATEEXECUTED" TIMESTAMP (6) NOT NULL ENABLE, 
	"ORDEREXECUTED" NUMBER(*,0) NOT NULL ENABLE, 
	"EXECTYPE" VARCHAR2(10) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MD5SUM" VARCHAR2(35) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COMMENTS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TAG" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LIQUIBASE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"CONTEXTS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LABELS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DEPLOYMENT_ID" VARCHAR2(10) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."UXI_ORDERS_LU" 
   (	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_TOTAL" NUMBER(8,2), 
	"ORDER_TIMESTAMP" TIMESTAMP (6), 
	"USER_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"TAGS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "UXI_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."CONTACT_US" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EMAIL_ADDRESS" VARCHAR2(400) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(4000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "CONTACT_US_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."UXI_AUTHN_METHODS_LU" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"METHOD" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "AUTHN_METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."UXI_FEATURE_CARDS_LU" 
   (	"CARD_TEXT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_IMAGE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_CATEGORY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_SUBTEXT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_ORDER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."DATABASECHANGELOG_ACTIONS" 
   (	"ID" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SEQUENCE" NUMBER NOT NULL ENABLE, 
	"SQL" CLOB COLLATE "USING_NLS_COMP", 
	"SXML" CLOB COLLATE "USING_NLS_COMP", 
	"AUTHOR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FILENAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DEPLOYMENT_ID" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "DATABASECHANGELOG_ACTIONS_PK" PRIMARY KEY ("ID", "AUTHOR", "FILENAME", "SEQUENCE")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/

/

/

/

/

/

/

/

/
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEMO"."DATABASECHANGELOG_DETAILS" ("DEPLOYMENT_ID", "ID", "AUTHOR", "FILENAME", "SQL", "SXML", "DATEEXECUTED", "EXECTYPE", "MD5SUM", "DESCRIPTION", "COMMENTS", "LIQUIBASE", "CONTEXTS", "LABELS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT  da.deployment_id,    da.id,    da.author,    da.filename,  da.sql,     da.sxml,    d.dateexecuted,    d.exectype,    d.md5sum,  d.description,    d.comments,    d.liquibase,    d.contexts,    d.labels 
FROM DEMO.DATABASECHANGELOG d  LEFT JOIN DEMO.DATABASECHANGELOG_ACTIONS da ON d.id = da.id AND d.author = da.author AND d.filename = da.filename ORDER BY   1,7
/
ALTER TABLE "DEMO"."DATABASECHANGELOG_ACTIONS" ADD CONSTRAINT "DATABASECHANGELOG_ACTIONS_PK" PRIMARY KEY ("ID", "AUTHOR", "FILENAME", "SEQUENCE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."UXI_DATA_SRC_LU" ADD CONSTRAINT "UXI_DATA_SRC_LU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."DATABASECHANGELOGLOCK" ADD CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."UXI_ORDERS_LU" ADD CONSTRAINT "UXI_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."CONTACT_US" ADD CONSTRAINT "CONTACT_US_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."UXI_AUTHN_METHODS_LU" ADD CONSTRAINT "AUTHN_METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."DATABASECHANGELOG_ACTIONS_TRG" BEFORE
    INSERT ON DEMO.DATABASECHANGELOG_ACTIONS
    FOR EACH ROW
DECLARE
    new_seq  NUMBER;
BEGIN
    SELECT
        nvl(MAX(sequence + 1), 0)
    INTO new_seq
    FROM
        DEMO.DATABASECHANGELOG_ACTIONS
    WHERE
            id = :new.id
        AND author = :new.author
        AND filename = :new.filename;

    :new.sequence := new_seq;
END;

ALTER TRIGGER "DEMO"."DATABASECHANGELOG_ACTIONS_TRG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."UXI_BI_AUTHN_METHODS_LU" 
  before insert on "UXI_AUTHN_METHODS_LU"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "UXI_AUTHN_METHODS_LU_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end;

ALTER TRIGGER "DEMO"."UXI_BI_AUTHN_METHODS_LU" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."BI_CONTACT_US" 
  before insert on "CONTACT_US"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "CONTACT_US_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

ALTER TRIGGER "DEMO"."BI_CONTACT_US" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."UXI_BI_DATA_SRC_LU" 
  before insert on "UXI_DATA_SRC_LU"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "UXI_DATA_SRC_LU_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end;

ALTER TRIGGER "DEMO"."UXI_BI_DATA_SRC_LU" ENABLE
/
10 10
/

BEGIN 
 
COMMIT; 
END;
/