CREATE TABLE "DEMO"."UXI_DATA_SRC_LU" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"POSSIBLE" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 'Y' NOT NULL ENABLE, 
	 CONSTRAINT "UXI_DATA_SRC_LU_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."UXI_ORDERS_LU" 
   (	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_TOTAL" NUMBER(8,2), 
	"ORDER_TIMESTAMP" TIMESTAMP (6), 
	"USER_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"TAGS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "UXI_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."CONTACT_US" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"EMAIL_ADDRESS" VARCHAR2(400) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(4000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "CONTACT_US_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."UXI_AUTHN_METHODS_LU" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"METHOD" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "AUTHN_METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."UXI_FEATURE_CARDS_LU" 
   (	"CARD_TEXT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_IMAGE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_CATEGORY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_SUBTEXT" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CARD_ORDER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP"
/

/

/

/

/

/
ALTER TABLE "DEMO"."UXI_DATA_SRC_LU" ADD CONSTRAINT "UXI_DATA_SRC_LU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."UXI_ORDERS_LU" ADD CONSTRAINT "UXI_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."CONTACT_US" ADD CONSTRAINT "CONTACT_US_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."UXI_AUTHN_METHODS_LU" ADD CONSTRAINT "AUTHN_METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."UXI_BI_AUTHN_METHODS_LU" 
  before insert on "UXI_AUTHN_METHODS_LU"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "UXI_AUTHN_METHODS_LU_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end;

ALTER TRIGGER "DEMO"."UXI_BI_AUTHN_METHODS_LU" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."BI_CONTACT_US" 
  before insert on "CONTACT_US"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "CONTACT_US_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

ALTER TRIGGER "DEMO"."BI_CONTACT_US" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."UXI_BI_DATA_SRC_LU" 
  before insert on "UXI_DATA_SRC_LU"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "UXI_DATA_SRC_LU_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end;

ALTER TRIGGER "DEMO"."UXI_BI_DATA_SRC_LU" ENABLE
/