CREATE TABLE "DEMO"."DATABASECHANGELOGLOCK" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LOCKED" NUMBER(1,0) NOT NULL ENABLE, 
	"LOCKGRANTED" TIMESTAMP (6), 
	"LOCKEDBY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."DATABASECHANGELOG" 
   (	"ID" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"AUTHOR" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DATEEXECUTED" TIMESTAMP (6) NOT NULL ENABLE, 
	"ORDEREXECUTED" NUMBER(*,0) NOT NULL ENABLE, 
	"EXECTYPE" VARCHAR2(10) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MD5SUM" VARCHAR2(35) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COMMENTS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TAG" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LIQUIBASE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"CONTEXTS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LABELS" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DEPLOYMENT_ID" VARCHAR2(10) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE "DEMO"."DATABASECHANGELOG_ACTIONS" 
   (	"ID" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SEQUENCE" NUMBER NOT NULL ENABLE, 
	"SQL" CLOB COLLATE "USING_NLS_COMP", 
	"SXML" CLOB COLLATE "USING_NLS_COMP", 
	"AUTHOR" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FILENAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"DEPLOYMENT_ID" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "DATABASECHANGELOG_ACTIONS_PK" PRIMARY KEY ("ID", "AUTHOR", "FILENAME", "SEQUENCE")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/

/

/

/
ALTER TABLE "DEMO"."DATABASECHANGELOG_ACTIONS" ADD CONSTRAINT "DATABASECHANGELOG_ACTIONS_PK" PRIMARY KEY ("ID", "AUTHOR", "FILENAME", "SEQUENCE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
ALTER TABLE "DEMO"."DATABASECHANGELOGLOCK" ADD CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."DATABASECHANGELOG_ACTIONS_TRG" BEFORE
    INSERT ON DEMO.DATABASECHANGELOG_ACTIONS
    FOR EACH ROW
DECLARE
    new_seq  NUMBER;
BEGIN
    SELECT
        nvl(MAX(sequence + 1), 0)
    INTO new_seq
    FROM
        DEMO.DATABASECHANGELOG_ACTIONS
    WHERE
            id = :new.id
        AND author = :new.author
        AND filename = :new.filename;

    :new.sequence := new_seq;
END;

ALTER TRIGGER "DEMO"."DATABASECHANGELOG_ACTIONS_TRG" ENABLE
/